<?php
/**
 * @file
 * Extend services to allow API key authentication on endpoints.
 */

/**
 * Implements hook_services_authentication_info().
 */
function services_api_key_auth_services_authentication_info() {
  return array(
    'title' => 'API key authentication',
    'description' => 'Enable API Key authentication for an endpoint.',
    'authenticate_call' => 'services_api_key_auth_services_authenticate',
    'security_settings' => 'services_api_key_auth_services_settings_form',
  );
}

/**
 * Apply authentication rules.
 */
function services_api_key_auth_services_authenticate() {
  // Get function arguments.
  $args = func_get_args();
  // Get the key from the request.
  $api_key = (!empty($_REQUEST['api-key'])) ? $_REQUEST['api-key'] : '';
  // Validate request.
  $valid = (services_api_key_auth_compare_key($api_key, $args[0]['api_key'])) ? TRUE : FALSE;
  // Allow other modules to have their say.
  drupal_alter('services_api_key_valid', $valid, $args);
  if ($valid) {
    // If a valid request, switch to user to perform drupal response.
    if (!empty($args[0]['user'])) {
      global $user;
      $current_user = user_load_by_name($args[0]['user']);
      if (!empty($current_user)) {
        $user = $current_user;
        drupal_session_regenerate();
        drupal_add_http_header('Cache-Control', 'no-cache, must-revalidate, post-check=0, pre-check=0');
      }
    }
    return FALSE;
  }
  //return services_error('Unauthorised access.', 401);
}

/**
 * Build form for authentication settings.
 *
 * @param $settings
 *   The settings as they exist currently.
 * @return
 *   The form definition.
 */
function services_api_key_auth_services_settings_form($settings) {
  $form = array();

  // Generate an API key for the user.
  $key = services_api_key_auth_generate_key();
  if ($key === FALSE) {
    $key = '';
  }

  // Text field for api key.
  $form['api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#description' => t('Enter an API key to allow access to this endpoint. You can use a secure pseudo-random key generated on your behalf, "!key", entered automatically if the field was empty.', array(
      '!key' => $key,
    )),
    '#default_value' => (!empty($settings['api_key'])) ? $settings['api_key'] : $key,
  );
  // Get list of users with given role.
  $role = user_role_load_by_name(variable_get('service_api_key_role', 'administrator'));
  $query = 'SELECT DISTINCT(ur.uid) FROM {users_roles} AS ur WHERE ur.rid = :rids';
  $result = db_query($query, array(':rids' => $role->rid));
  $options = array('' => 'Select user');
  while ($uid = $result->fetchColumn()) {
    $user = user_load($uid);
    $options[$user->name] = $user->name;
    unset($user);
  }
  // Build select field.
  $form['user'] = array(
    '#type' => 'select',
    '#title' => t('User'),
    '#description' => t('Select the user to run request through this endpoint as.'),
    '#options' => $options,
    '#default_value' => (!empty($settings['user'])) ? $settings['user'] : '',
  );
  return $form;
}

/**
 * Compare api key.
 *
 * @param $a string
 *   Token string.
 * @param $b string
 *   Token string.
 *
 * @return boolean
 */
function services_api_key_auth_compare_key($a, $b) {
  if (strlen($a) !== strlen($b)) {
    return FALSE;
  }
  $result = 0;
  for ($i = 0; $i < strlen($a); $i++) {
    $result |= ord($a[$i]) ^ ord($b[$i]);
  }
  return $result == 0;
}

/**
 * Implements hook_menu().
 */
function services_api_key_auth_menu() {
  return array(
    'admin/structure/services/api_key_settings' => array(
      'title' => t('API Key settings'),
      'description' => t('Set user role for user list in API Key authentication settings.'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('services_api_key_auth_admin_settings'),
      'access arguments' => array('administer services'),
      'type' => MENU_LOCAL_TASK,
    ),
  );
}

/**
 * Define form for admin screen.
 *
 * @see services_api_key_auth_admin_settings_submit()
 */
function services_api_key_auth_admin_settings() {
  // Get available roles.
  $roles = user_roles();
  // Build field options.
  $options = array();
  foreach ($roles as $role) {
    $options[$role] = $role;
  }
  // Build form.
  $form = array();
  $form['fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('User settings'),
    '#description' => t('Set the user role to be used when loading the list of users to pick from when configuring the API Key Authentication settings on an endpoint.'),
  );
  $form['fieldset']['role'] = array(
    '#type' => 'select',
    '#title' => t('User role'),
    '#options' => $options,
    '#default_value' => variable_get('service_api_key_role', 'administrator'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );
  return $form;
}

/**
 * Process admin form submission.
 *
 * @see services_api_key_auth_admin_settings()
 */
function services_api_key_auth_admin_settings_submit($form, &$state) {
  variable_set('service_api_key_role', $state['values']['role']);
  drupal_set_message('Settings saved.');
}

/**
 * Generate a secure pseudo-random key.
 *
 * The function will generate a secure pseudo-random UUID for use as an API key.
 *
 * @return
 *   The generated key, or FALSE on the inability to generate one.
 */
function services_api_key_auth_generate_key() {
  // Set the number of random characters we'll need.
  $num_chars = 16;

  // Generate a random string of 16 characters as securely as possible. This is
  // largely taken from http://stackoverflow.com/a/15875555/442022. Note that we
  // can't use random_bytes() because that's only for PHP 7+.
  if (function_exists('openssl_random_pseudo_bytes')) {
    // The OpenSSL library is available so we can use its function.
    $random_data = openssl_random_pseudo_bytes($num_chars);
  }
  else if (file_exists('/dev/urandom')) {
    // As we don't have OpenSSL, grab random data from the pool on UNIX-like
    // systems.
    $random_data = file_get_contents('/dev/urandom', NULL, NULL, 0, $num_chars);
  }
  else {
    // We're not on a UNIX-like system, and are missing the OpenSSL library.
    // Report failure as this situation isn't supported.
    drupal_set_message(t('As you have neither the OpenSSL library, nor a UNIX-like system, we were unable to generate a secure pseudo-random key for you.'), 'warning');
    return FALSE;
  }

  // Set parts of the string to match the UUID specifications.
  // Set version to 0100.
  $random_data[6] = chr(ord($random_data[6]) & 0x0f | 0x40);
  // Set bits 6-7 to 10.
  $random_data[8] = chr(ord($random_data[8]) & 0x3f | 0x80);

  // Format the string properly, and then return it.
  return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($random_data), 4));
}
